### PR TITLE
get rid of SITE_ID (for multiple site installation)

### PR DESCRIPTION
**Pull request by gassan**
subj

### CODE REVIEW

**Comment by danirus** [comment]
Thanks @gassan for taking the time to do this.

I would prefer not to wrap `django.contrib.sites.shortcuts.get_current_site`. I haven't seen any Django project using this package without `django.contrib.sites` installed, however I think it's safe to have the fallback you added when there's no `pk` attribute.

Did you consider `getattr(get_current_site(request), "pk", 1)` instead of creating `utils.get_site_id`?

The CI issues are most probably because you go beyond column 79. I would appreciate if you could keep that constraint.
Thanks again.

**Comment by gassan** [comment]
> Did you consider `getattr(get_current_site(request), "pk", 1)` instead of creating `utils.get_site_id`?

Good idea - I will use `getattr` and fix line lengths later this week

**Comment by gassan** [comment]
I need the shortcut utils.get_current_site_id - this function is called 11 times.

**Comment by gassan** [comment]
use pip<19 for install from github.
pip install git+https://github.com/gassan/django-comments-xtd.git@nositeid

**Comment by danirus** [comment]
Thanks @gassan, 
and sorry for the long delay.

**Pull request merged**
